### ISSUE TITLE
Undo

### ISSUE THREAD

**Issue by vlangberg** [gdietz/OpenMEE#185] opened 2015-04-15 05:56 UTC
Ctrl+z and the undo button do not always work.

**Comment by bwallace** [comment] 2015-04-15 13:48
We need more information here. Can you describe the exact sequence of steps
to reproduce the problem please?

On Wed, Apr 15, 2015 at 12:56 AM, vlangberg <notifications@github.com>
wrote:

> Ctrl+z and the undo button do not always work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdietz/OpenMEE/issues/185>.
>



-- 
byron

**Comment by gdietz** [comment] 2015-04-19 21:22
@vlangberg +1 to Byron's comment. Undo doesn't come for free, we have to choose to include it. Letting us know where it doesn't work would be useful.

**Comment by vlangberg** [comment] 2015-04-21 16:53
Changing the contents of a cell can't be undone.  For example, if I have all of my data entered and I accidentally clear a cell of data, ctrl+z does nothing.

**Comment by gdietz** [comment] 2015-04-27 05:23
@vlangberg Can you describe the exact circumstances under which this is occurring? I need step by step instructions starting from 'launch the program'. Providing data files in the dropbox would be helpful too. I tried to replicate what you described above but when I clear a cell and then press ⌘-z (undo on mac), the original value returns.

**Comment by vlangberg** [comment] 2015-06-03 18:55
Here is a video of the circumstances under which ctrl+z was not working:
https://vlangber.tinytake.com/sf/MTM4NzkzXzg3NjI0Nw

**Comment by gdietz** [comment] 2015-06-08 03:27
Ah ok, this shouldn't be too hard to fix.

**Comment by gdietz** [comment] 2016-06-13 02:30
I can't reproduce this so closing out.

**Closed by gdietz** 2016-06-13 02:30 UTC
Labels: high priority
